name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: zip -r e-commerce-app.zip dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: e-commerce-app-artifact
          path: e-commerce-app.zip

